name: 'BAO Jibe'
description: 'Sync shop commits from 1 repo to another'
inputs:
  destination-repository-name:
    description: 'The repository we want to sync changes to'
    required: true
  target-branch:
    description: 'The branch we want to get changes on'
    required: true
    default: 'master'
  BAO_API_TOKEN:
    description: 'The branch we want to get changes on'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
