on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          destination-repository-name: 'debut-src'
        env:
          BAO_API_TOKEN: ${{ secrets.BAO_API_TOKEN }}

#jobs:
#  bao_jibe:
#    runs-on: ubuntu-latest
#    name: A job to say hello
#    steps:
#      - name: Hello world action step
#        id: hello
#        with:
#          destination-repository-name: 'debut-src'
#          target-branch: 'master'
#          BAO_API_TOKEN: ${{ secrets.BAO_API_TOKEN }}
#      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
